### ISSUE TITLE
Extra software is installed

### ISSUE THREAD

**Issue by samalloing** [openpreserve/ViPER#11]
Hi @carlwilson (cc @aniamolenda)

I don't know if this is relevant, but the Debian installation includes lots of extra software that is maybe not needed like Evolution. For software like LibreOffice, Gimp, Inkscape there is some case to be made. But for example Games is maybe not necessary ;-) It will make the download also smaller.

Sam

**Comment by carlwilson** [comment]
Hi @samalloing and thanks for the detailed feedback. I've considered paring back the software installed but had seen the task as a late optimisation one. There are two options:
- go with a stripped-down OS or equivalent vagrant box where the cruft has been removed by somebody else;
- remove the appropriate packages via ansible here: https://github.com/openpreserve/ddhn-forge/blob/master/ansible/roles/ddhn.setup/tasks/prerequisites.yml which currently adds dependencies but could remove packages on another list here: https://github.com/openpreserve/ddhn-forge/blob/master/ansible/roles/ddhn.setup/defaults/main.yml#L3
I think I'd try for a cutback distro first, there's probably an official Debian version to try.

**Comment by carlwilson** [comment]
Used debian guide to thin out the OS (games, etc.) but be conservative. 4 hours effort

**Comment by carlwilson** [comment]
There will be a top-level removal of "cruft" for the next release in June. I'll probably approach this iteratively over the next two or three revisions. Proceed carefully in case something needs replacing.
