### ISSUE TITLE
beta ova file doesn't start in VirtualBox v5.2.44

### ISSUE THREAD

**Issue by cannedit** [openpreserve/ViPER#29]
Hi,

I volunteered for testing the VRE, downloaded the beta ova file over here: https://ddhn.openpreservation.org/ddhn-beta.ova and tried to get that installed in my already existing VirtualBox v5.2.44 (with Extension pack), but it generates and error (attached). Is something wrong with this ova file or can it only be used in the latest version of VirtualBox, so v6.x?

![NDE_VRE_Install_error_VirtualBox_v5 2 44](https://user-images.githubusercontent.com/22167327/98831293-aa136400-243b-11eb-9a07-8c243c08be7a.png)

**Comment by tledoux** [comment]
Hi, I volunter to.
I got the same error than you with my already installed Virtual Box 5.1.30.

Upgrading to the latest 6.1.16, makes the import successfull.

To be noted the installation of VirtualBox is fast, but the importation of the .ova takes about 30 minutes...

**Comment by cannedit** [comment]
Hi, 

Ok, I switched to another computer (a Windows 7 system, the other one was a Windows 10 system), installed VirtualBox 6.1.16 and could now indeed install the beta ova file.

However, when trying to run it I got into trouble again: the system gave one error and two warnings, but I couldn't follow up on the suggestions to solve these because the options I had to change are all greyed out, so I got stuck again (see the screenshots attached).

Btw: the fact that the ova file can only be imported into a VirtualBox v6.x version should be in the manual; I know: officially the VirtualBox v5.x versions are not supported anymore, but a lot of people might still use these versions.

![NDE_VRE_VirtualBox6_1](https://user-images.githubusercontent.com/22167327/98864553-5f5d1080-246a-11eb-97a8-a125325f46f7.png)
![NDE_VRE_VirtualBox6_2](https://user-images.githubusercontent.com/22167327/98864556-608e3d80-246a-11eb-89df-e182075d94ad.png)
![NDE_VRE_VirtualBox6_3](https://user-images.githubusercontent.com/22167327/98864557-608e3d80-246a-11eb-92e7-b95b828d31b0.png)
![NDE_VRE_VirtualBox6_4](https://user-images.githubusercontent.com/22167327/98864558-6126d400-246a-11eb-9a7d-ac4665a0c386.png)
![NDE_VRE_VirtualBox6_5](https://user-images.githubusercontent.com/22167327/98864560-6126d400-246a-11eb-82fb-83f5b535ae53.png)
![NDE_VRE_VirtualBox6_6](https://user-images.githubusercontent.com/22167327/98864561-6126d400-246a-11eb-83af-b7d886516029.png)

**Comment by cannedit** [comment]
Hi,

NDE was so kind to provide a new beta ova file (https://ddhn.openpreservation.org/ddhn-beta.ova) and I could make some progress using that, so I was able to change and save the setting of the second network adapter, but after the installation was finished I briefly saw the VRE screen passing by on my screen, but then I ended up with a Vagrant login screen:
![NDE_VRE_New_ova_01](https://user-images.githubusercontent.com/22167327/100217077-57de4280-2f13-11eb-8887-baee222e3356.png)
![NDE_VRE_New_ova_02](https://user-images.githubusercontent.com/22167327/100217083-5876d900-2f13-11eb-9277-4880e918703e.png)
![NDE_VRE_New_ova_03](https://user-images.githubusercontent.com/22167327/100217085-5876d900-2f13-11eb-9364-419476d74a7e.png)
![NDE_VRE_New_ova_04_16](https://user-images.githubusercontent.com/22167327/100217087-590f6f80-2f13-11eb-9c88-9527a4301fef.png)

**Comment by cannedit** [comment]
Hi,

I tried again, using the ddhn-rc.ova, and now it worked (and I didn't had to change the network adapters):

![NDE_VRE_rc-ova](https://user-images.githubusercontent.com/22167327/101403991-4cf1bd80-38d6-11eb-8568-5a1b4ca5623d.png)

**Comment by carlwilson** [comment]
@cannedit thanks so much for your feedback, apologies for not being more proactive with replies. I can confirm that there were two issues, a misconfiguration of the virtual box extensions that only manifested itself intermittently and a rogue network adapter that was a by-product of the automated creation. I believe that they're both fixed in the RC and thanks for giving me cause for optimisim.

**Comment by carlwilson** [comment]
We believe this is fixed @cannedit and we will close this shortly unless we hear differently.
