### ISSUE TITLE
Documentation on file sharing and tools

### ISSUE THREAD

**Issue by tledoux** [openpreserve/ViPER#31]
It seems to me that one of the goals of the VRE is been able to validate or transform files with the tools provided.
Since the files will come from outside the VRE, the file sharing is a key aspect of VRE ; the documentation seems a little too lazy to me. 

Indeed, describing this customize step and defining a specific mount point (like /data or /mnt/data) in the VRE, seem a great way to unify the way the tools will read and write the files.

Finally, if such a mount point is defined, the tools could be preset to interact with it, simplifying the interaction for the final user.

**Comment by carlwilson** [comment]
Thanks for the update @tledoux and would agree that the documentation probably makes too many assumptions around Virtual Box experience. A getting started guide is underway, we will look to provide some better information. A standard mount point sounds like an excellent idea.

**Comment by carlwilson** [comment]
4 hours document and close.
