### ISSUE TITLE
Documentation - Maintainer's Guide

### ISSUE THREAD

**Issue by MerleFri** [openpreserve/ViPER#39]
https://openpreserve.github.io/ddhn-forge/maintainer/

I miss a short introduction covering in which situations I would use this guide.

The paragraph provisioning could state clearer where Ansible is installed, is it my computer or is it the virtual machine? How do I set up the SSH access to the target machine (if the explanation is to long, maybe a link)?

**Comment by carlwilson** [comment]
I'm closing this. IMO the guide makes the intended audience pretty clear and it's not intended to provide documentation that is available online, e.g. Ansible or SSH.
