### ISSUE TITLE
Additional Tool: siegfried

### ISSUE THREAD

**Issue by MerleFri** [openpreserve/ViPER#41]
siegfried (https://www.itforarchivists.com/siegfried/) is another file format identifier, good to compare the results with DROID or Apache Tika.

**Comment by kieranjol** [comment]
+1

**Comment by carlwilson** [comment]
Having reviewed this, I realise that the lack of a GUI and the GO dependency means Siegfried currently falls outside of the selection criteria for the VRE. While I can see the utility the policy is currently GUI tools first.
